repos:
  - repo: local
    hooks:
      - id: uv-env-sync
        name: UV Env Sync
        entry: zsh ./pre-commit-uv-env-sync.sh
        language: system
        always_run: true
        pass_filenames: false
        stages: [ commit ]
        args: [ "--allow-modifications" ]
