name: ci

on:
  push:
    branches:
      - main
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read Commit ID
        id: commit_id
        run: echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Read Build Date
        id: build_date
        run: echo "BUILD_AT=$(date -u +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

      - name: Verify Environment Variables
        run: echo "COMMIT_ID=${{ env.COMMIT_ID }} BUILD_AT=${{ env.BUILD_AT }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: akkk1234/oleapi:latest
          build-args: |
            COMMIT_ID=${{ env.COMMIT_ID }}
            BUILD_AT=${{ env.BUILD_AT }}


      - name: Dokploy Deployment
        uses: benbristow/dokploy-deploy-action@0.0.1
        with:
          auth_token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          application_id: ${{ secrets.DOKPLOY_APPLICATION_ID }}
          dokploy_url: ${{ secrets.DOKPLOY_URL }}