name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Read .env file
        id: dotenv
        run:  |
          echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "PUSH_TIME=${{ github.event.head_commit.timestamp }}" >> $GITHUB_ENV

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64

          push: true
          tags: akkk1234/oleapi:latest
          build-args: |
            COMMIT_ID=${{ env.COMMIT_ID }}
            BUILD_AT=${{ env.PUSH_TIME }}
            VCS_REF=${{ env.COMMIT_ID }}
      - name: trigger deploy webhook
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"token": ${{ secrets.DEPLOY_TOKEN }}}' ${{ secrets.DEPLOY_WEBHOOK }}
            
